# Generated by Django 5.1 on 2026-04-11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='analysisreport',
            name='phenoage_delta_years',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True, verbose_name='Diferencia edad biológica-cronológica'),
        ),
        migrations.AddField(
            model_name='analysisreport',
            name='phenoage_missing',
            field=models.TextField(blank=True, default='', verbose_name='Marcadores faltantes para PhenoAge'),
        ),
        migrations.AddField(
            model_name='analysisreport',
            name='phenoage_years',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True, verbose_name='Edad biológica (PhenoAge)'),
        ),
    ]
