# Generated by Django 5.2.13 on 2026-04-11 17:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labs', '0002_analysisreport_phenoage_fields'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='analysisreport',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_reports', to=settings.AUTH_USER_MODEL, verbose_name='Usuario'),
        ),
        migrations.CreateModel(
            name='BodyCompositionReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nombre')),
                ('date', models.DateField(verbose_name='Fecha')),
                ('notes', models.TextField(blank=True, verbose_name='Notas')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado el')),
                ('weight', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Peso (kg)')),
                ('height', models.DecimalField(decimal_places=1, max_digits=5, verbose_name='Altura (cm)')),
                ('body_fat_pct', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Grasa corporal (%)')),
                ('visceral_fat', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True, verbose_name='Grasa visceral (nivel)')),
                ('muscle_mass', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Masa muscular (kg)')),
                ('water_pct', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Agua (%)')),
                ('protein_pct', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Proteína (%)')),
                ('bone_mass', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Masa ósea (kg)')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_reports', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Composición corporal',
                'verbose_name_plural': 'Composiciones corporales',
                'ordering': ['-date', '-created_at'],
                'abstract': False,
            },
        ),
    ]
