# Generated by Django 5.1 on 2026-04-11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('labs', '0002_analysisreport_phenoage_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='ECGReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nombre')),
                ('date', models.DateField(verbose_name='Fecha')),
                ('notes', models.TextField(blank=True, verbose_name='Notas')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado el')),
                ('image', models.ImageField(upload_to='ecg/%Y/%m/', verbose_name='Imagen de ECG')),
                ('rhythm_frequency', models.CharField(blank=True, help_text='Ej: Ritmo sinusal a 60 lpm', max_length=500, verbose_name='Ritmo y frecuencia')),
                ('interpretation', models.TextField(blank=True, help_text='Hallazgos y observaciones del ECG', verbose_name='Interpretación clínica')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ecgreport_reports', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Electrocardiograma',
                'verbose_name_plural': 'Electrocardiogramas',
                'ordering': ['-date', '-created_at'],
            },
        ),
    ]
