# Generated by Django 5.2.13 on 2026-04-11 19:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('labs', '0003_body_composition'),
        ('labs', '0004_ecg_report'),
    ]

    operations = [
    ]
