# Generated by Django 5.2.13 on 2026-04-11 19:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labs', '0005_merge_0003_body_composition_0004_ecg_report'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='ecgreport',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_reports', to=settings.AUTH_USER_MODEL, verbose_name='Usuario'),
        ),
    ]
