# Generated by Django 5.2.13 on 2026-04-12 09:51

import labs.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labs', '0006_alter_ecgreport_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ecgreport',
            name='interpretation',
        ),
        migrations.RemoveField(
            model_name='ecgreport',
            name='rhythm_frequency',
        ),
        migrations.AddField(
            model_name='ecgreport',
            name='heart_rate',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Frecuencia cardíaca (bpm)'),
        ),
        migrations.AlterField(
            model_name='ecgreport',
            name='image',
            field=models.ImageField(upload_to=labs.models.ECGReport.ecg_image_upload_path, verbose_name='Imagen de ECG'),
        ),
    ]
