# Generated by Django 5.2.13 on 2026-04-12 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labs', '0007_remove_ecgreport_interpretation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='avatars/', verbose_name='Foto de perfil'),
        ),
    ]
